version: 1

trail:
  attestations:
    - name: creator
      type: snyk
    - name: custom-start-points
      type: snyk
    - name: dashboard
      type: snyk
    - name: differ
      type: snyk
    - name: exercises-start-points
      type: snyk
    - name: languages-start-points
      type: snyk
    - name: nginx
      type: snyk
    - name: saver
      type: snyk
    - name: web
      type: snyk
