 name: Github Action with a cronjob trigger
 on:
   schedule:  # Midnight every day
     - cron: "0 0 * * *"

 jobs:
   cronjob-based-github-action:
     name: Cronjob based github action
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
     - uses: entepotenz/keep-github-actions-alive-min-dependencies@v1
