name: main

on:
  workflow_dispatch:
  schedule: # At 09:00 every morning
    - cron: '0 9 * * *'


jobs:
  report-beta:
    uses: cyber-dojo/snyk_scans/.github/workflows/snyk_scan_live_artifacts_and_report_any_new_vulnerabilities_to_kosli.yml@main
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      AWS_ACCOUNT_ID: 244531986313
      AWS_REGION: eu-central-1
      KOSLI_HOST: https://app.kosli.com
      CYBER_DOJO_ENVIRONMENT: aws-beta

  report-prod:
    uses: cyber-dojo/snyk_scans/.github/workflows/snyk_scan_live_artifacts_and_report_any_new_vulnerabilities_to_kosli.yml@main
    secrets:
      KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    with:
      AWS_ACCOUNT_ID: 274425519734
      AWS_REGION: eu-central-1
      KOSLI_HOST: https://app.kosli.com
      CYBER_DOJO_ENVIRONMENT: aws-prod