name: Run Periodic Snyk Scan

on: 
  push:
  schedule:
    - cron: '0 9 * * *'



env: 
  KOSLI_ORG: cyber-dojo
  KOSLI_CLI_VERSION: "2.6.0"
  KOSLI_TEMPLATE: "artifact,snyk-scan"
  # KOSLI_DRY_RUN: "True"
  KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}


jobs:

  snyk-scan:
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup kosli cli
        uses: kosli-dev/setup-cli-action@v2
        with:
          version:
            ${{ env.KOSLI_CLI_VERSION }}

      # Snyk scan ------------------
      - name: Setup Snyk
        uses: snyk/actions/setup@master

      - name: Run Snyk to check Docker images for new vulnerabilities
        continue-on-error: true
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run:
          ./scan_all_images.sh


  
